all:
  hosts:
    web01:
      ansible_host: 172.31.21.17
      ansible_user: ec2-user
      ansible_ssh_private_key_file: clientkey.pem
    web02:
      ansible_host: 172.31.24.11
      ansible_user: ec2-user
      ansible_ssh_private_key_file: clientkey.pem
    db01:
      ansible_host: 172.31.31.2
      ansible_user: ec2-user
      ansible_ssh_private_key_file: clientkey.pem
      # Grouping
  children:
    webservers:
      hosts:
        web01:
        web02:
    dbservers:
      hosts:
        db01:
    dc_oregon:
      children:
        webservers:
        dbservers:
