Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0fff1b9a61dec8a5f
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: !Join ["-", ['My', 'instance', 'from' 'cloudformation']]
      SecurityGroups:
           - !Ref VprofileSG

  VprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh & http to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 70.51.71.98/32