apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-deployment
  labels:
    app: sample-python-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-python-deployment
  template:
    metadata:
      labels:
        app: sample-python-deployment
    spec:
      containers:
      - name: sample-python
        image: festusosayi/python-sample-web-app:V1
        ports:
        - containerPort: 8000

